apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "grafana.server.configname" . }}
data:
{{- range .Values.extraGrafanaConfigs }}
{{ toYaml . | indent 2 }}
{{- end }}
